# Generated by Django 3.0.6 on 2020-05-26 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_city',
            field=models.CharField(default='', max_length=75, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_state',
            field=models.CharField(default='', max_length=50, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_street',
            field=models.CharField(default='', max_length=200, verbose_name='Street Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_zip',
            field=models.CharField(default='', max_length=50, verbose_name='ZIP Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved to post on this site.', verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
    ]
