# Generated by Django 3.0.6 on 2020-06-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sullivan_coins_balance',
            field=models.FloatField(default=5.0),
        ),
    ]
