# Generated by Django 3.0.6 on 2020-06-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200517_1832'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(related_name='offers', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='request',
            name='categories',
            field=models.ManyToManyField(related_name='requests', to='categories.Category'),
        ),
    ]
