# Generated by Django 3.0.6 on 2020-05-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200527_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='request',
            name='tags',
        ),
    ]
