# Generated by Django 3.0.6 on 2020-05-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200528_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
