# Generated by Django 3.0.6 on 2021-04-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20210406_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='tasks.TaskCategory'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='parent_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='tasks.TaskCategory'),
        ),
    ]
