# Generated by Django 3.0.6 on 2021-04-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210406_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskavailability',
            options={'verbose_name': 'Task Availability', 'verbose_name_plural': 'Task Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'Task Category', 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.AlterField(
            model_name='taskavailability',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tasks.Task'),
        ),
    ]
