# Generated by Django 3.2.3 on 2021-07-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_taskcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
