# Generated by Django 3.2.3 on 2021-07-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'User Message', 'verbose_name_plural': 'User Messages'},
        ),
    ]
