# Generated by Django 3.2.3 on 2021-07-26 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_messages', '0003_auto_20210724_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessagethread',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usermessagethread',
            name='recipient',
        ),
        migrations.AddField(
            model_name='usermessagethread',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_thread_participants', to='users.customuser'),
            preserve_default=False,
        ),
    ]
